config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"

  resources :payments, only: [:new, :create]
  resources :payouts, only: [:index, :new, :create] do
    resources :transactions, only: [:index]
  end
  resources :transactions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :name, presence: true, uniqueness: true

	has_many :transactions
	has_many :payouts
end

app/models/payment.rb
class Payment
	include ActiveModel::Model

  attr_accessor(
    :payment_type,
    :card_number,
    :exp_month,
    :exp_year,
    :cvc,
    :billing_zip,
    :account_number,
    :routing_number,
    :amount_cents,
    :bill_me_on,
    :merchant_id
  )

  validates :payment_type, presence: true
  validates :amount_cents, presence: true
  validates :merchant_id, presence: true

  validates :card_number, presence: true, if: :is_card_type?
  validates :exp_month, :format => { :with => /[0-9]/, :message => "Not a valid digit number" }, presence: true, if: :is_card_type?
  validates :exp_year, :format => { :with => /[0-9]/, :message => "Not a valid digit number" }, presence: true, if: :is_card_type?
  validates :cvc, :format => { :with => /[0-9]/, :message => "Not a valid digit number" }, presence: true, if: :is_card_type?
  validates :billing_zip, :format => { :with => /[0-9]/, :message => "Not a valid digit number" }, presence: true, if: :is_card_type?
  validate  :card_number_value, if: :is_card_type?

  validates :account_number, :format => { :with => /[0-9]/, :message => "Not a valid digit number" }, presence: true, if: :is_bank_account_type?
  validates :routing_number, presence: true, if: :is_bank_account_type?
  validate  :routing_number_value, if: :is_bank_account_type?

  def make_payment
    if valid?
      ActiveRecord::Base.transaction do
        payment_source = PaymentSource.create!(payment_type: payment_type, card_number: card_number, exp_month: exp_month,
                                              exp_year: exp_year, cvc: cvc, billing_zip: billing_zip,
                                              account_number: account_number, routing_number: routing_number,
                                              state: 'create')
        Transaction.create!(amount_cents: amount_cents, bill_me_on: bill_me_on, payment_source_id: payment_source.id, merchant_id: merchant_id)
      end
    else
    	false
    end
  end

  private

  def card_number_value
    if card_number.match('^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$')
      return true
    else
      self.errors.add(:card_number, "Invalid card_number")
    end
  end

  def routing_number_value
    return true if RoutingNumber.find_by(number: routing_number)
    self.errors.add(:routing_number, "Invalid routing_number")
  end

  def is_card_type?
    payment_type == 'Card'
  end

  def is_bank_account_type?
    payment_type == 'Bank'
  end
end

app/models/payment_source.rb
class PaymentSource < ApplicationRecord
	has_many :transactions

  # ATTR_ENCRYPTED_KEY should be an environment variable
  # We should also filter these params from the logs
  ATTR_ENCRYPTED_KEY = "nFSeSCCzsw0gALaKZCw9GayqzdPBnD1C"

  attr_encrypted :card_number, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :exp_month, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :exp_year, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :cvc, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :billing_zip, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :account_number, key: ATTR_ENCRYPTED_KEY
  attr_encrypted :routing_number, key: ATTR_ENCRYPTED_KEY
end

app/models/payout.rb
class Payout < ApplicationRecord
  belongs_to :merchant
	has_many :transactions

  before_validation :merchant_has_unpaid_txns
  before_validation :calculate_payment
  after_commit :update_transactions, on: :create

  monetize :fee_charged, as: :fee_charged_cents
  monetize :amount, as: :amount_cents


  def update_transactions
    unpaid_transactions = merchant.transactions.unpaid
    unpaid_transactions.update_all(payout_id: self.id, state: 'paid')
  end

  def merchant_has_unpaid_txns
    return true if merchant.transactions.unpaid.any?
    self.errors.add(:base, "Merchant has no unpaid transactions")
  end

  def calculate_payment
    total_fee_charged = 0
    total_amount = 0

    merchant.transactions.unpaid.find_each do |txn|
      txn_amount_cents = txn.amount_cents.cents
      processing_fee = processing_fee(txn_amount_cents, txn.payment_source.payment_type)
      total_fee_charged += processing_fee
      total_amount += txn_amount_cents - processing_fee
    end

    self.fee_charged = total_fee_charged
    self.amount = total_amount
  end

  def processing_fee(amount, payment_type)
    if payment_type == 'Bank'
      (amount * (1 * 0.01)).round + 100
    else
      (amount * (2.9 * 0.01)).round + 30
    end
  end
end

app/models/routing_number.rb
class RoutingNumber < ApplicationRecord
  validates :number, presence: true, uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  scope :unpaid, -> { where(state: 'created') }
  scope :paid, -> { where(state: 'paid') }

	belongs_to :merchant
	belongs_to :payment_source, optional: true
	belongs_to :payout, optional: true

  monetize :amount, as: :amount_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
  end

  def new
  	@payment = Payment.new
  end

  def create
  	@payment = Payment.new(payment_params)

  	if @payment.make_payment
      flash[:notice] = 'Payment was creted'
      redirect_to root_path
  	else
  		render :new
  	end
  end

  private

  def payment_params
    params.require(:payment).permit(:payment_type, :merchant_id, :amount_cents, :bill_me_on,
    																:card_number, :exp_month, :exp_year, :cvc, :billing_zip,
    																:account_number, :routing_number)
  end
end

app/controllers/payouts_controller.rb
class PayoutsController < ApplicationController

  def index
    @payouts = Payout.all
  end

  def new
  	@payout = Payout.new
  end

  def create
    @payout = Payout.new(payout_params)

    if @payout.save
      flash[:notice] = 'Payout was created'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def payout_params
    params.require(:payout).permit(:merchant_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    begin
      if params[:payout_id]
        @transactions = Transaction.where(payout_id: params[:payout_id])
      elsif params[:search].present?
        date = Date.parse(params[:search], '%m_%d_%Y')
        @transactions = Transaction.where(created_at: date.beginning_of_day..date.end_of_day)
      else
        @transactions = Transaction.all
      end
    rescue ArgumentError => e
      @transactions = Transaction.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    "error" => "danger",
    "warning" => "warning",
    "notice" => "success",
    "alert" => "warning"
  }
  
  def display_flash
    return if flash.empty?
    flash.map do |key, value|
      content_tag :div, value, class: "alert alert-#{BOOTSTRAP_ALERT_CLASS[key] || "info"}" unless key == 'timedout'
    end.join("").html_safe
  end

  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "card border-danger") do
        concat(content_tag(:div, class: "card-header bg-danger text-white") do
        	'Fix The Following Errors'
        end)
        concat(content_tag(:div, class: "card-body") do
            concat(content_tag(:ul, class: 'mb-0') do
                object.errors.full_messages.each do |msg|
                    concat content_tag(:li, msg)
                end
            end)
        end)
      end
    end
  end
end

app/views/dashboard/index.html.erb
<h1>Menu</h1>
<ul class="b">
  <li><%= link_to 'Make Payment', new_payment_path %></li>
  <li><%= link_to 'Create Payout', new_payout_path %></li>
  <li><%= link_to 'Transactions', transactions_path %></li>
  <li><%= link_to 'Payouts', payouts_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= display_flash %>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: @payment, local: true, class: "form-horizontal m-5") do |form| %>
  <% if @payment.errors.any? %>
  <%= errors_for(@payment) %>
  <% end %>
  <div class="row">
      <div class="col-md-12">
          <div>
              <div class="card-default card">
                  <div class="card-body">
                      <fieldset>
                          <div class="position-relative row form-group">
                              <%= form.label :payment_type, class: 'col-md-3 col-form-label' %>
                              <div class="col-md-9">
                                  <%= form.select :payment_type, ['Card', 'Bank'],{},{ class: "form-select cardselect"} %>
                              </div>
                          </div>
                      </fieldset>
                      <fieldset>
                          <div class="position-relative row form-group">
                              <%= form.label :merchant_id, class: 'col-md-3 col-form-label' %>
                              <div class="col-md-9">
                                  <%= form.collection_select :merchant_id, Merchant.all, :id, :name, {include_blank: false}, {class: "form-control"} %>
                              </div>
                          </div>
                      </fieldset>
                      <fieldset>
                          <div class="position-relative row form-group">
                              <%= form.label :amount_cents, class: 'col-md-3 col-form-label' %>
                              <div class="col-md-9">
                                  <%= form.text_field :amount_cents, placeholder: '1,234.23', maxlength: 15, class: "form-control maskmoney" %>
                              </div>
                          </div>
                      </fieldset>
                      <fieldset>
                          <div class="position-relative row form-group">
                              <%= form.label :bill_me_on, class: 'col-md-3 col-form-label' %>
                              <div class="col-md-9">
                                  <%= form.text_field :bill_me_on, class: "form-control", id: 'datepicker' %>
                              </div>
                          </div>
                      </fieldset>
                      <div class="card_fields">
                          <fieldset>
                              <div class="position-relative row form-group">
                                  <%= form.label :card_number, class: 'col-md-3 col-form-label' %>
                                  <div class="col-md-9">
                                      <%= form.text_field :card_number, maxlength: '16', placeholder: '4242424242424242', class: "form-control" %>
                                  </div>
                              </div>
                          </fieldset>
                          <fieldset>
                              <div class="position-relative row form-group">
                                  <div class="col-md-4">
                                      <%= form.label :exp_month, class: 'col-md-3 col-form-label' %>
                                      <div class="col-md-9">
                                          <%= form.text_field :exp_month, maxlength: '2', placeholder: '08', class: "form-control" %>
                                      </div>
                                  </div>
                                  <div class="col-md-4">
                                      <%= form.label :exp_year, class: 'col-md-3 col-form-label' %>
                                      <div class="col-md-9">
                                          <%= form.text_field :exp_year, maxlength: '4', placeholder: '2025', class: "form-control" %>
                                      </div>
                                  </div>
                          </fieldset>
                          <fieldset>
                              <div class="position-relative row form-group">
                                  <div class="col-md-4">
                                      <%= form.label :cvc, class: 'col-md-3 col-form-label' %>
                                      <div class="col-md-9">
                                          <%= form.text_field :cvc, maxlength: '3', placeholder: '121', class: "form-control" %>
                                      </div>
                                  </div>
                                  <div class="col-md-4">
                                      <%= form.label :billing_zip, class: 'col-md-3 col-form-label' %>
                                      <div class="col-md-9">
                                          <%= form.text_field :billing_zip, maxlength: '7', placeholder: '12345', class: "form-control" %>
                                      </div>
                                  </div>
                          </fieldset>
                      </div>
                      <div class="bank_fields" style="display: none;">
                          <fieldset>
                              <div class="position-relative row form-group">
                                  <%= form.label :account_number, class: 'col-md-3 col-form-label' %>
                                  <div class="col-md-9">
                                      <%= form.text_field :account_number, class: "form-control" %>
                                  </div>
                              </div>
                          </fieldset>
                          <fieldset>
                              <div class="position-relative row form-group">
                                  <%= form.label :routing_number, class: 'col-md-3 col-form-label' %>
                                  <div class="col-md-9">
                                      <%= form.text_field :routing_number, class: "form-control" %>
                                  </div>
                              </div>
                          </fieldset>
                      </div>
                  </div>
                  <div class="card-footer">
                      <div class="float-right">
                          <%= form.submit 'Submit', class: "btn btn-lg btn-primary" %>
                          <%= link_to 'Back', root_path, class: "btn btn-lg btn-secondary", role: "button" %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
<% end %>
<div class="footer">
  <%= link_to "Menu" , root_path %>
</div>

app/views/payments/index.html.erb
<h1>Menu</h1>
<ul class="b">
  <li><%= link_to 'Make Payment', new_payment_path %></li>
  <li><%= link_to 'Create Payout', new_payout_path %></li>
  <li><%= link_to 'Transactions', transactions_path %></li>
  <li><%= link_to 'Payouts', payouts_path %></li>
</ul>
<div class="footer">
  <%= link_to "Menu" , root_path %>
</div>

app/views/payments/new.html.erb
<%= render partial: 'form' %>

app/views/payouts/_form.html.erb
<%= form_with(model: @payout, local: true, class: "form-horizontal m-5") do |form| %>
  <% if @payout.errors.any? %>
  <%= errors_for(@payout) %>
  <% end %>
  <div class="row">
      <div class="col-md-12">
          <div>
              <div class="card-default card">
                  <div class="card-body">
                    <fieldset>
                        <div class="position-relative row form-group">
                            <%= form.label :merchant_id, class: 'col-md-3 col-form-label' %>
                            <div class="col-md-9">
                                <%= form.collection_select :merchant_id, Merchant.all, :id, :name, {include_blank: false}, {class: "form-control"} %>
                            </div>
                        </div>
                    </fieldset>
                  </div>
                  <div class="card-footer">
                      <div class="float-right">
                          <%= form.submit 'Submit', class: "btn btn-lg btn-primary" %>
                          <%= link_to t('back'), root_path, class: "btn btn-lg btn-secondary", role: "button" %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
<% end %>
<div class="footer">
  <%= link_to "Menu" , root_path %>
</div>

app/views/payouts/index.html.erb
<h1>Payouts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Payout Amount</th>
      <th>Fee Charged</th>
      <th>Merchant</th>
      <th>Transactions</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
    <% @payouts.each do |payout| %>
      <tr>
        <td><%= humanized_money_with_symbol payout.amount_cents%></td>
        <td><%= humanized_money_with_symbol payout.fee_charged_cents%></td>
        <td><%= payout.merchant.name%></td>
        <td><%= link_to "Link", payout_transactions_path(payout_id: payout.id)%></td>
      </tr>
    <% end %>
</table>
<div class="footer">
  <%= link_to "Menu" , root_path %>
</div>

app/views/payouts/new.html.erb
<%= render partial: 'form' %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<%= form_tag(transactions_path, method: :get) do %>
  <p> Select a Date </p>
  <%= text_field_tag(:search, params[:search], id: 'datepicker') %>
  <%= submit_tag ("Search") %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Bill Me On</th>
      <th>Merchant</th>
      <th>Payment Type</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
    <% @transactions.each do |txn| %>
      <tr>
        <td><%= humanized_money_with_symbol txn.amount_cents%></td>
        <td><%= txn.bill_me_on&.strftime("%m/%d/%Y")%></td>
        <td><%= txn.merchant.name%></td>
        <td><%= txn.payment_source.payment_type%></td>
      </tr>
    <% end %>
</table>
<div class="footer">
  <%= link_to "Menu" , root_path %>
</div>